import mongoose from 'mongoose';

const studentSchema = new mongoose.Schema({
  name: { type: String, required: true },
  class: { type: String, required: true },
  rollNumber: { type: String, required: true, unique: true },
  email: { type: String, required: true },
  phone: { type: String, required: true },
  address: { type: String },
  school: { type: String },
  joiningDate: { type: Date },
  // Credentials - generated by teacher
  passwordHash: { type: String }, // Hashed password (generated randomly)
  plainPassword: { type: String }, // Store plain password temporarily for display (cleared after first login)
  credentialsGenerated: { type: Boolean, default: false },
  isFirstLogin: { type: Boolean, default: true }, // Track if student needs to change password
  teacherId: { type: String, required: true }, // Teacher ID who created the student (e.g., "Ajay123")
  createdAt: { type: Date, default: Date.now }
}, {
  timestamps: true
});

const Student = mongoose.model('Student', studentSchema);

export default Student;
