import mongoose from "mongoose";

const studentSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    class: { type: String, required: true },
    rollNumber: { type: String, required: true, unique: true },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    address: { type: String },
    school: { type: String },
    joiningDate: { type: Date },
    // Credentials - generated by teacher
    passwordHash: { type: String }, // Hashed password (generated randomly)
    plainPassword: { type: String }, // Store plain password temporarily for display (cleared after first login)
    credentialsGenerated: { type: Boolean, default: false },
    isFirstLogin: { type: Boolean, default: true }, // Track if student needs to change password
    teacherId: { type: String, required: true }, // Teacher ID who created the student (e.g., "Ajay123")

    // Points and Progress
    points: { type: Number, default: 0 },
    todayPoints: { type: Number, default: 0 },
    lastPointsDate: { type: Date },
    streak: { type: Number, default: 0 },
    level: { type: Number, default: 1 },
    currentXP: { type: Number, default: 0 },
    nextLevelXP: { type: Number, default: 100 },
    badges: { type: Number, default: 0 },
    hoursLearned: { type: Number, default: 0 },

    // Daily challenges - array format
    dailyChallenges: [
      {
        id: { type: String },
        type: { type: String },
        title: { type: String },
        description: { type: String },
        xpReward: { type: Number },
        completed: { type: Boolean, default: false },
        completedAt: { type: Date },
      },
    ],
    dailyChallengeCompleted: { type: Boolean, default: false },

    // Watched videos tracking
    watchedVideos: [
      {
        syllabusId: { type: mongoose.Schema.Types.ObjectId, ref: "Syllabus" },
        watchedAt: { type: Date, default: Date.now },
        pointsEarned: { type: Number, default: 0 },
      },
    ],

    // Quiz scores / Completed Quizzes
    quizScores: [
      {
        syllabusId: { type: mongoose.Schema.Types.ObjectId, ref: "Syllabus" },
        score: { type: Number },
        completedAt: { type: Date, default: Date.now },
      },
    ],

    // Completed quizzes with points tracking
    completedQuizzes: [
      {
        syllabusId: { type: mongoose.Schema.Types.ObjectId, ref: "Syllabus" },
        quizTitle: { type: String },
        score: { type: Number },
        pointsAwarded: { type: Number, default: 0 },
        completedAt: { type: Date, default: Date.now },
      },
    ],

    createdAt: { type: Date, default: Date.now },
  },
  {
    timestamps: true,
  }
);

const Student = mongoose.model("Student", studentSchema);

export default Student;
