import fetch from 'node-fetch';

/**
 * AI Grading Service - Uses Google Gemini API for assignment verification
 * Includes plagiarism detection, topic relevance, content quality analysis
 */

class AIGradingService {
  constructor() {
    this.apiKey = process.env.GEMINI_API_KEY;
    this.apiUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';
  }

  /**
   * Send request to Gemini API
   */
  async callGeminiAPI(prompt) {
    try {
      const response = await fetch(`${this.apiUrl}?key=${this.apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }],
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 4096,
          }
        })
      });

      if (!response.ok) {
        throw new Error(`Gemini API error: ${response.status}`);
      }

      const data = await response.json();
      return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
    } catch (error) {
      console.error('Gemini API Error:', error);
      throw error;
    }
  }

  /**
   * Parse JSON from AI response
   */
  parseJSONResponse(text) {
    try {
      // Try to extract JSON from the response
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        return JSON.parse(jsonMatch[0]);
      }
      return null;
    } catch (error) {
      console.error('JSON Parse Error:', error);
      return null;
    }
  }

  /**
   * Check topic relevance of the assignment
   */
  async checkTopicRelevance(content, topic, subject) {
    const prompt = `
You are an expert academic evaluator. Analyze if the following assignment content is relevant to the given topic and subject.

SUBJECT: ${subject}
EXPECTED TOPIC: ${topic}

ASSIGNMENT CONTENT:
${content.substring(0, 8000)}

Evaluate and respond in this exact JSON format only:
{
  "score": <number 0-100>,
  "isRelevant": <boolean>,
  "keyTopicsFound": ["topic1", "topic2"],
  "missingTopics": ["missing1", "missing2"],
  "feedback": "Detailed feedback about topic relevance"
}

Rules:
- Score 80-100: Highly relevant, covers the topic well
- Score 60-79: Moderately relevant, covers main points
- Score 40-59: Partially relevant, misses key aspects
- Score below 40: Off-topic or barely relevant
- isRelevant should be true if score >= 50
`;

    const response = await this.callGeminiAPI(prompt);
    const result = this.parseJSONResponse(response);
    
    return result || {
      score: 0,
      isRelevant: false,
      keyTopicsFound: [],
      missingTopics: [],
      feedback: 'Unable to analyze topic relevance'
    };
  }

  /**
   * Detect plagiarism in content
   */
  async detectPlagiarism(content) {
    const prompt = `
You are an expert plagiarism detection system. Analyze the following text for signs of plagiarism, copied content, or unoriginal work.

CONTENT TO ANALYZE:
${content.substring(0, 8000)}

Look for:
1. Unusual writing style changes within the text
2. Technical jargon inconsistent with overall writing level
3. Phrases that appear to be copied from common sources
4. Lack of original thought or analysis
5. Perfect grammar in some sections vs errors in others
6. Wikipedia-style or textbook-style writing patterns

Respond in this exact JSON format only:
{
  "score": <number 0-100 representing plagiarism percentage>,
  "isPlagiarized": <boolean - true if score > 30>,
  "suspiciousSegments": [
    {
      "text": "suspicious text segment",
      "similarity": <number 0-100>,
      "reason": "why this seems plagiarized"
    }
  ],
  "feedback": "Overall plagiarism assessment"
}

Be strict but fair. Academic work should be original.
`;

    const response = await this.callGeminiAPI(prompt);
    const result = this.parseJSONResponse(response);
    
    return result || {
      score: 0,
      isPlagiarized: false,
      suspiciousSegments: [],
      feedback: 'Unable to perform plagiarism check'
    };
  }

  /**
   * Detect AI-generated content
   */
  async detectAIContent(content) {
    const prompt = `
You are an AI content detection expert. Analyze if the following text appears to be generated by AI (like ChatGPT, Claude, etc.) rather than written by a human student.

CONTENT TO ANALYZE:
${content.substring(0, 8000)}

Look for these AI writing patterns:
1. Overly perfect structure and flow
2. Generic, non-specific examples
3. Lack of personal voice or unique perspective
4. Perfect grammar throughout
5. Repetitive transition phrases
6. Lack of specific personal experiences or local references
7. Overly balanced and neutral tone
8. Common AI phrases like "It's important to note", "In conclusion", etc.

Respond in this exact JSON format only:
{
  "score": <number 0-100 representing probability of AI generation>,
  "isAIGenerated": <boolean - true if score > 60>,
  "indicators": ["indicator1", "indicator2"],
  "feedback": "Detailed analysis of AI content detection"
}
`;

    const response = await this.callGeminiAPI(prompt);
    const result = this.parseJSONResponse(response);
    
    return result || {
      score: 0,
      isAIGenerated: false,
      indicators: [],
      feedback: 'Unable to perform AI content detection'
    };
  }

  /**
   * Analyze content quality
   */
  async analyzeContentQuality(content, topic, subject) {
    const prompt = `
You are an expert academic evaluator. Analyze the quality of this student assignment.

SUBJECT: ${subject}
TOPIC: ${topic}

ASSIGNMENT CONTENT:
${content.substring(0, 8000)}

Evaluate the following aspects and respond in this exact JSON format only:
{
  "score": <overall quality score 0-100>,
  "grammar": <grammar score 0-100>,
  "clarity": <clarity and readability score 0-100>,
  "depth": <depth of analysis and understanding score 0-100>,
  "structure": <organization and structure score 0-100>,
  "feedback": "Detailed feedback on content quality",
  "strengths": ["strength1", "strength2"],
  "improvements": ["improvement1", "improvement2"]
}

Scoring guide:
- 90-100: Exceptional work, exceeds expectations
- 80-89: Very good work, meets all requirements well
- 70-79: Good work, meets most requirements
- 60-69: Satisfactory, meets basic requirements
- 50-59: Below average, needs improvement
- Below 50: Unsatisfactory, major improvements needed
`;

    const response = await this.callGeminiAPI(prompt);
    const result = this.parseJSONResponse(response);
    
    return result || {
      score: 0,
      grammar: 0,
      clarity: 0,
      depth: 0,
      structure: 0,
      feedback: 'Unable to analyze content quality',
      strengths: [],
      improvements: []
    };
  }

  /**
   * Calculate final grade based on all scores
   */
  calculateGrade(scores) {
    const { topicRelevance, plagiarism, aiContent, contentQuality } = scores;
    
    // If plagiarism is high, severely penalize
    if (plagiarism.score > 50) {
      return {
        totalScore: Math.max(0, 30 - plagiarism.score / 2),
        grade: 'F',
        passed: false,
        reason: 'High plagiarism detected'
      };
    }
    
    // If AI content is high, penalize
    if (aiContent.score > 70) {
      return {
        totalScore: Math.max(0, 40 - aiContent.score / 3),
        grade: 'F',
        passed: false,
        reason: 'AI-generated content detected'
      };
    }
    
    // If off-topic, penalize
    if (!topicRelevance.isRelevant) {
      return {
        totalScore: Math.min(40, topicRelevance.score),
        grade: 'F',
        passed: false,
        reason: 'Assignment is off-topic'
      };
    }
    
    // Calculate weighted score
    let totalScore = (
      topicRelevance.score * 0.25 +
      contentQuality.score * 0.40 +
      (100 - plagiarism.score) * 0.20 +
      (100 - aiContent.score) * 0.15
    );
    
    // Determine grade
    let grade;
    if (totalScore >= 95) grade = 'A+';
    else if (totalScore >= 90) grade = 'A';
    else if (totalScore >= 85) grade = 'A-';
    else if (totalScore >= 80) grade = 'B+';
    else if (totalScore >= 75) grade = 'B';
    else if (totalScore >= 70) grade = 'B-';
    else if (totalScore >= 65) grade = 'C+';
    else if (totalScore >= 60) grade = 'C';
    else if (totalScore >= 55) grade = 'C-';
    else if (totalScore >= 50) grade = 'D';
    else grade = 'F';
    
    return {
      totalScore: Math.round(totalScore),
      grade,
      passed: totalScore >= 50
    };
  }

  /**
   * Complete assignment verification
   */
  async verifyAssignment(content, topic, subject) {
    console.log('Starting AI verification...');
    
    // Run all checks in parallel for efficiency
    const [topicRelevance, plagiarism, aiContent, contentQuality] = await Promise.all([
      this.checkTopicRelevance(content, topic, subject),
      this.detectPlagiarism(content),
      this.detectAIContent(content),
      this.analyzeContentQuality(content, topic, subject)
    ]);

    // Calculate final grade
    const finalGrade = this.calculateGrade({
      topicRelevance,
      plagiarism,
      aiContent,
      contentQuality
    });

    // Generate flags
    const flags = [];
    
    if (plagiarism.isPlagiarized) {
      flags.push({
        type: 'plagiarism',
        severity: plagiarism.score > 50 ? 'critical' : 'high',
        message: `Plagiarism detected: ${plagiarism.score}%`
      });
    }
    
    if (aiContent.isAIGenerated) {
      flags.push({
        type: 'ai_content',
        severity: aiContent.score > 80 ? 'critical' : 'high',
        message: `AI-generated content suspected: ${aiContent.score}%`
      });
    }
    
    if (!topicRelevance.isRelevant) {
      flags.push({
        type: 'off_topic',
        severity: topicRelevance.score < 30 ? 'critical' : 'medium',
        message: `Assignment appears off-topic: ${topicRelevance.score}% relevance`
      });
    }
    
    if (contentQuality.score < 50) {
      flags.push({
        type: 'low_quality',
        severity: contentQuality.score < 30 ? 'high' : 'medium',
        message: `Low content quality: ${contentQuality.score}%`
      });
    }

    return {
      isVerified: true,
      verifiedAt: new Date(),
      topicRelevance: {
        score: topicRelevance.score,
        isRelevant: topicRelevance.isRelevant,
        feedback: topicRelevance.feedback,
        keyTopicsFound: topicRelevance.keyTopicsFound || [],
        missingTopics: topicRelevance.missingTopics || []
      },
      plagiarismCheck: {
        score: plagiarism.score,
        isPlagiarized: plagiarism.isPlagiarized,
        suspiciousSegments: plagiarism.suspiciousSegments || [],
        feedback: plagiarism.feedback
      },
      contentQuality: {
        score: contentQuality.score,
        grammar: contentQuality.grammar,
        clarity: contentQuality.clarity,
        depth: contentQuality.depth,
        structure: contentQuality.structure,
        feedback: contentQuality.feedback
      },
      aiContentDetection: {
        score: aiContent.score,
        isAIGenerated: aiContent.isAIGenerated,
        feedback: aiContent.feedback
      },
      overallAssessment: {
        totalScore: finalGrade.totalScore,
        grade: finalGrade.grade,
        passed: finalGrade.passed,
        detailedFeedback: this.generateDetailedFeedback(topicRelevance, plagiarism, aiContent, contentQuality, finalGrade),
        strengths: contentQuality.strengths || [],
        areasForImprovement: contentQuality.improvements || []
      },
      flags
    };
  }

  /**
   * Generate detailed feedback
   */
  generateDetailedFeedback(topicRelevance, plagiarism, aiContent, contentQuality, finalGrade) {
    let feedback = `## Assignment Evaluation Summary\n\n`;
    feedback += `**Overall Grade: ${finalGrade.grade} (${finalGrade.totalScore}/100)**\n\n`;
    
    feedback += `### Topic Relevance (${topicRelevance.score}/100)\n`;
    feedback += `${topicRelevance.feedback}\n\n`;
    
    feedback += `### Content Quality (${contentQuality.score}/100)\n`;
    feedback += `- Grammar: ${contentQuality.grammar}/100\n`;
    feedback += `- Clarity: ${contentQuality.clarity}/100\n`;
    feedback += `- Depth: ${contentQuality.depth}/100\n`;
    feedback += `- Structure: ${contentQuality.structure}/100\n`;
    feedback += `${contentQuality.feedback}\n\n`;
    
    if (plagiarism.score > 10) {
      feedback += `### ⚠️ Plagiarism Alert (${plagiarism.score}% detected)\n`;
      feedback += `${plagiarism.feedback}\n\n`;
    }
    
    if (aiContent.score > 40) {
      feedback += `### ⚠️ AI Content Detection (${aiContent.score}% probability)\n`;
      feedback += `${aiContent.feedback}\n\n`;
    }
    
    if (!finalGrade.passed) {
      feedback += `### ❌ Assignment Did Not Pass\n`;
      feedback += `Please review the feedback and resubmit after making improvements.\n`;
    } else {
      feedback += `### ✅ Assignment Passed\n`;
      feedback += `Good job! Continue to improve based on the feedback provided.\n`;
    }
    
    return feedback;
  }
}

export default new AIGradingService();
